### ISSUE TITLE
error received - attempt 3 [book borrowed]

### ISSUE THREAD

**Issue by seasaltseasalt** [scoliono/archiveripper#5]
Hello
I still have not managed to get title successful. I must be doing something stupid. Can you please lmk how I can test i have set up correctly.

Steps performed
1 Borrowed book as normal in account
2 In terminal ran the ripper.py script 

i entered book ID
ii entered login credentials
script runs then returns error in terminal

Traceback (most recent call last):
  File "/Users/author/Library/Python/3.7/lib/python/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/Users/author/Library/Python/3.7/lib/python/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/author/Library/Python/3.7/lib/python/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred...

[error continued][then at end]

Traceback (most recent call last):
  File "ripper.py", line 101, in <module>
    main()
  File "ripper.py", line 54, in main
    page_count = client.fetch_book_metadata()
  File "/Users/xx/D/MAC/api.py", line 106, in fetch_book_metadata
    res = self.session.get(self.URL_FORMAT % ('details/' + self.book_id))
  File "/Users/xx/Library/Python/3.7/lib/python/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/Users/xx/Library/Python/3.7/lib/python/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/xx/Library/Python/3.7/lib/python/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/xx/Library/Python/3.7/lib/python/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

thankyou

**Comment by BirchBoy** [comment]
This problem seems to happen for me when I try to use my web-browser and this at the same time.
