### ISSUE TITLE
Error: No host supplied

### ISSUE THREAD

**Issue by antonmohorcic** [scoliono/archiveripper#9]
$python3 ./ripper.py 
Look for the book's identifier (the part of the url immediately after "https://archive.org/details/").
Enter it here: introductiontonu0000alle
Enter your archive.org email: **********@*****.com
Enter your archive.org password: 
Output folder ./introductiontonu0000alle already exists. Continue? yes
Traceback (most recent call last):
  File "/home/anton/Downloads/archiveripper-master/./ripper.py", line 92, in <module>
    main()
  File "/home/anton/Downloads/archiveripper-master/./ripper.py", line 59, in main
    page_count = client.fetch_book_metadata()
  File "/home/anton/Downloads/archiveripper-master/api.py", line 109, in fetch_book_metadata
    res = self.session.get('https:' + match.group(1))
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/lib/python3/dist-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 445, in prepare_url
    raise InvalidURL(f"Invalid URL {url!r}: No host supplied")
requests.exceptions.InvalidURL: Invalid URL 'https:{"isBeta":false,"br_ui":null,"urlHistoryBasePath":"/details/introductiontonu0000alle/","resumeCookiePath":"/details/introductiontonu0000alle","initialSearchTerm":null,"purchase_url":"","has_multiple_readable_files":false,"multipleBooksList":{"by_subprefix":{"introductiontonu0000alle":{"url_path":"/details/introductiontonu0000alle","file_subprefix":"introductiontonu0000alle","title":"introductiontonu0000alle_orig_jp2.tar","file_source":"/introductiontonu0000alle_jp2.zip","orig_sort":0}},"main_dir":"/33/items/introductiontonu0000alle"},"autofit":"auto","url":"//ia803003.us.archive.org/BookReader/BookReaderJSIA.php?id=introductiontonu0000alle\\u0026itemPath=/33/items/introductiontonu0000alle\\u0026server=ia803003.us.archive.org\\u0026format=jsonp\\u0026subPrefix=introductiontonu0000alle\\u0026requestUri=/details/introductiontonu0000alle"}': No host supplied

**Comment by notevenaperson** [comment]
This was fixed in othellodesutter's fork: https://github.com/othellodesutter/archiveripper so you can use theirs.

I also had to port the fix to [my fork](https://github.com/notevenaperson/archiveripper).

**Comment by scoliono** [comment]
Fixed in 6bf64dd
